Resources branch top section code changes
aggarwalkartik555/unconstrained-app pull request #6
Opened 2023-10-13 14:48 UTC by aggarwalkartik555

2023-10-14 02:54 UTC, vigilantee requested changes

2023-10-14 02:54 UTC, vigilantee commented on src/components/resources/data.js
> +export default data;
add a new line here..

2023-10-14 02:54 UTC, vigilantee commented on src/components/resources/resources.css
> +}
add a new line.

2023-10-16 10:42 UTC, aggarwalkartik555 commented on src/components/resources/data.js
> +export default data;
done

2023-10-16 10:42 UTC, aggarwalkartik555 commented on src/components/resources/resources.css
> +}
done

2023-10-17 08:13 UTC, vigilantee approved these changes

2023-10-17 08:13 UTC, merged